var icons = [
  {
    name: "CPU",
    src: "cpu",
    tags: ["cpu", "computer", "pc", "electronics", "processing"],
  },
  {
    name: "Monitor",
    src: "monitor",
    tags: ["monitor", "tv", "display", "computer"],
  },
  { name: "File", src: "file", tags: ["file, document"] },
  { name: "Text File", src: "file_text", tags: ["file, text, document"] },
  {
    name: "Credit Card",
    src: "creditcard",
    tags: [
      "payment",
      "pay",
      "audio",
      "card",
      "credit",
      "creditcard",
      "money",
      "bank",
    ],
  },
  {
    name: "Speaker",
    src: "speaker",
    tags: ["sound", "audio", "noise", "speaker"],
  },
  {
    name: "Bug",
    src: "bug",
    tags: [
      "bug",
      "insect",
      "programming",
      "debug",
      "debugging",
      "critter",
      "roach",
      "beatle",
      "coding",
      "develop",
      "developing",
      "developer",
      "programmer",
      "issue",
      "problem",
    ],
  },
  { name: "Phone", src: "phone", tags: ["phone", "iphone", "mobile"] },
  {
    name: "Battery 100%",
    src: "battery100",
    tags: [
      "battery",
      "charge",
      "energy",
      "charger",
      "charged",
      "charging",
      "electricity",
      "power",
    ],
  },
  {
    name: "Battery 75%",
    src: "battery75",
    tags: [
      "battery",
      "charge",
      "energy",
      "charger",
      "charged",
      "charging",
      "electricity",
      "power",
    ],
  },
  {
    name: "Battery 50%",
    src: "battery50",
    tags: [
      "battery",
      "charge",
      "energy",
      "charger",
      "charged",
      "charging",
      "electricity",
      "power",
    ],
  },
  {
    name: "Battery 25%",
    src: "battery25",
    tags: [
      "battery",
      "charge",
      "energy",
      "charger",
      "charged",
      "charging",
      "electricity",
      "power",
    ],
  },
  {
    name: "Battery 10%",
    src: "battery10",
    tags: [
      "battery",
      "charge",
      "energy",
      "charger",
      "charged",
      "charging",
      "electricity",
      "power",
    ],
  },
  {
    name: "Battery",
    src: "battery",
    tags: [
      "battery",
      "charge",
      "energy",
      "charger",
      "charged",
      "charging",
      "electricity",
      "power",
    ],
  },
  {
    name: "Clock",
    src: "clock",
    tags: ["clock", "time"],
  },
  {
    name: "RAM",
    src: "ram",
    tags: ["ram", "memory", 'computer', 'pc', 'electronics'],
  },
];
